#!/bin/bash

. ns import sv_id sv_name sv_syntax

sv-load 1>/dev/null # | grep -v "sv_file" | grep -v "sv_example_usage" | grep -v "sv_name" | grep -v "sv_syntax" | grep -v "sv_reference" | grep -v "sv_id"

# echo "$sv_name" 1>&2
# echo "$sv_syntax" 1>&2
# echo "$sv_reference" 1>&2
# echo "$sv_example_usage" 1>&2

tex="\\chapter{${sv_name}}"$'\n'

i=0
tex="${tex}{\\Large \$"$'\n'
while [[ $i -lt ${#sv_syntax} ]];
do
    if [[ "${sv_syntax:$i:1}" == "{" ]]; then
        tex="${tex}\\{"
    elif [[ "${sv_syntax:$i:1}" == "}" ]]; then
        tex="${tex}\\}"
    elif [[ "${sv_syntax:$i:1}" = "“" ]]; then
        tex="${tex}\`\`"
    elif [[ "${sv_syntax:$i:1}" = "”" ]]; then
        tex="${tex}''"
    elif [[ ${sv_syntax:$i:1} = *[![:ascii:]]* ]]; then
        tex="${tex}\${\\var{""${sv_syntax:$i:1}""}}\$"
    elif [[ "${sv_syntax:$i:1}" == " " ]]; then
        tex="${tex}\\s "
    else
        tex="${tex}${sv_syntax:$i:1}"
    fi
    ((i++))
done

tex="${tex}"$'\n'"\$"$'\n'"}"$'\n'

# tex="${tex}\\par"$'\n'
# 
# tex="${tex}\\tiny Reference: \\url{""${sv_reference}""}"$'\n'
# 
# tex="${tex}\\par"$'\n'
# 
# tex="${tex}\\tiny Example Usage: \\url{""${sv_example_usage}""}"$'\n'

echo "$tex"

. ns export sv_id sv_name sv_syntax
